### PR TITLE
[bug] Fix missing code

### PR DESCRIPTION
**Pull request by gmh5225**
Make `info.internal.hardware.enabled = true` when `Process::SetHardwareBreakpoint` return true

### CODE REVIEW

**Comment by mrexodia** [comment]
Thanks for your contribution!

**Comment by justanotheranonymoususer** [comment]
is this issue still in x64dbg? can you update it? just downloaded latest ver, hw bp doesn't get removed and I'm getting "bp not in list"

**Comment by mrexodia** [comment]
GleeBug has been updated to the latest version, so this change is definitely in!

**Comment by justanotheranonymoususer** [comment]
bummer, so not fixed in glee, I guess I need to go back to using titan, although I had other issues with it

**Pull request merged**
